language: node_js

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/waiter_availability_test

node_js:  
  - "12"

before_script:
  - psql -c 'create database waiter_availability_test;' -U postgres
  - psql -U postgres -d waiter_availability_test -a -f table.sql

services:
  - postgresql